$42.LEVEL_TYPE_GIVEN    = 1;
$42.LEVEL_TYPE_PREFIX   = 2;
$42.LEVEL_TYPE_FREE     = 3;
$42.LEVEL_MIN_PREFIX_CANDIDATES = 5;
$42.LEVEL_DEVS = {
    easy: [{                        // Easy Level 1
        type: $42.LEVEL_TYPE_GIVEN,
        words: 3,
        minValue:   0,        // min word value that is shown
        minDemand:  0,        // min word value that is enough for winning
        maxValue:   0,
        minLength:  5,
        maxLength:  6,
        newLetters: 2,
        prefGroups: null,
        wordFreq: 1.0
    },{                             // Level 2
        type: $42.LEVEL_TYPE_GIVEN,
        words: 3,
        minValue:   0,
        minDemand:  0,
        maxValue:   0,
        minLength:  6,
        maxLength:  7,
        newLetters: 2,
        prefGroups: null,
        wordFreq: 1.2
    },{                             // Level 3
        type: $42.LEVEL_TYPE_GIVEN,
        words: 3,
        minValue:   0,
        minDemand:  0,
        minLength:  7,
        maxLength:  8,
        newLetters: 2,
        prefGroups: null,
        wordFreq: 1.4
    },{                             // Level 4
        type: $42.LEVEL_TYPE_GIVEN,
        words: 3,
        minValue:   0,
        minDemand:  0,
        minLength:  9,
        maxLength: 10,
        newLetters: 2,
        prefGroups: null,
        wordFreq: 1.0
    }],

    intermediate: [{                // Intermediate Level 1
        type: $42.LEVEL_TYPE_PREFIX,
        words: 2,
        minValue:   0,
        minDemand:  0,
        minLength:  4,
        maxLength:  0,
        newLetters: 2,
        wordFreq: 1.3,
        fillInRate: 0.5,
        neededLettersProb: 0.3
    },{                             // Level 2
        type: $42.LEVEL_TYPE_PREFIX,
        words: 2,
        minValue:   0,
        minDemand:  0,
        minLength:  5,
        maxLength:  0,
        newLetters: 2,
        wordFreq: 1.6,
        fillInRate: 0.8,
        neededLettersProb: 0.25
    },{                             // Level 3
        type: $42.LEVEL_TYPE_PREFIX,
        words: 2,
        minValue:   0,
        minDemand:  0,
        minLength:  6,
        maxLength:  0,
        newLetters: 2,
        wordFreq: 1.8,
        fillInRate: 1,
        neededLettersProb: 0.5
    },{                             // Level 4
        type: $42.LEVEL_TYPE_PREFIX,
        words: 2,
        minValue:   0,
        minDemand:  0,
        minLength:  7,
        maxLength:  0,
        wordFreq: 1.8,
        fillInRate: 1,
        newLetters: 2,
    },{                             // Level 5
        type: $42.LEVEL_TYPE_PREFIX,
        words: 2,
        minValue:   0,
        minDemand:  0,
        minLength:  8,
        maxLength:  0,
        wordFreq: 1.8,
        fillInRate: 1,
        newLetters: 2,
    },{                             // Level 6
        type: $42.LEVEL_TYPE_PREFIX,
        words: 2,
        minValue:   0,
        minDemand:  0,
        minLength:  9,
        maxLength:  0,
        wordFreq: 1.8,
        fillInRate: 1,
        newLetters: 2,
    }],
    expert: [{                             // Level 1
        type: $42.LEVEL_TYPE_FREE,
        words: 1,
        minValue:   0,
        minDemand:  0,
        minLength:  0,
        maxLength:  0,
        newLetters: 2,
    },{                             // Level 2
        type: $42.LEVEL_TYPE_FREE,
        words: 1,
        minValue:   0,
        minDemand:  0,
        minLength:  0,
        maxLength:  0,
        newLetters: 2,
    },{                             // Level 3
        type: $42.LEVEL_TYPE_FREE,
        words: 1,
        minValue:   0,
        minDemand:  0,
        minLength:  0,
        maxLength:  0,
        newLetters: 2,
    },{                             // Level 4
        type: $42.LEVEL_TYPE_FREE,
        words: 1,
        minValue:   0,
        minDemand:  0,
        minLength:  0,
        maxLength:  0,
        newLetters: 2,
    },{                             // Level 5
        type: $42.LEVEL_TYPE_FREE,
        words: 1,
        minValue:   0,
        minDemand:  0,
        minLength:  0,
        maxLength:  0,
        newLetters: 2,
    },{                             // Level 6
        type: $42.LEVEL_TYPE_FREE,
        words: 1,
        minValue:   0,
        minDemand:  0,
        minLength:  0,
        maxLength:  0,
        newLetters: 2,
    },{                             // Level 7
        type: $42.LEVEL_TYPE_FREE,
        words: 1,
        minValue:   0,
        minDemand:  0,
        minLength:  0,
        maxLength:  0,
        newLetters: 2,
    },{                             // Level 8
        type: $42.LEVEL_TYPE_FREE,
        words: 1,
        minValue:   0,
        minDemand:  0,
        minLength:  0,
        maxLength:  0,
        newLetters: 2,
    },{                             // Level 9
        type: $42.LEVEL_TYPE_FREE,
        words: 1,
        minValue:   0,
        minDemand:  0,
        minLength:  0,
        maxLength:  0,
        newLetters: 2,
    },{                             // Level 10
        type: $42.LEVEL_TYPE_FREE,
        words: 1,
        minValue:   0,
        minDemand:  0,
        minLength:  0,
        maxLength:  0,
        newLetters: 2,
    },{                             // Level 11
        type: $42.LEVEL_TYPE_FREE,
        words: 1,
        minValue:   0,
        minDemand:  0,
        minLength:  0,
        maxLength:  0,
        newLetters: 2,
    },{                             // Level 12
        type: $42.LEVEL_TYPE_FREE,
        words: 1,
        minValue:   0,
        minDemand:  0,
        minLength:  0,
        maxLength:  0,
        newLetters: 2,
    }],
};

