var res = {
    tiles_png : "res/images/tiles/tiles.png",
    tiles_plist : "res/images/tiles/tiles.plist",
    letters_png : "res/images/letters/letters.png",
    letters_plist : "res/images/letters/letters.plist",
    tweet_png : "res/images/tweet/tweet.png",
    tweet_plist : "res/images/tweet/tweet.plist",
    title_easy_png : "res/images/title/title.png",
    title_intermediate_png : "res/images/title/title_2.png",
    title_expert_png : "res/images/title/title_3.png",
	background01_png : "res/images/backgrounds/level01.png",
	background02_png : "res/images/backgrounds/level02.png",
	background03_png : "res/images/backgrounds/level03.png",
	background04_png : "res/images/backgrounds/level04.png",
	background05_png : "res/images/backgrounds/level05.png",
	background06_png : "res/images/backgrounds/level06.png",
	background07_png : "res/images/backgrounds/level07.png",
	twitter_png : "res/images/backgrounds/twitter.png",
	wordfound_png : "res/images/backgrounds/wordfound.png",
    circles_png : "res/images/backgrounds/circles.png",
    circles_plist : "res/images/backgrounds/circles.plist",
	background_element1_png : "res/images/backgrounds/element1.png",
	background_element2_png : "res/images/backgrounds/element2.png",
    background_levelnr_png : "res/images/backgrounds/levelnr.png",
	empty_png : "res/empty.png",
	amtype24_png : "res/fonts/amtype24.png",
	amtype72_png : "res/fonts/amtype72.png",

	// sounds
    title_easy_intro_mp3 : "res/sounds/blaues_titelbild_einleitung0,1,16.mp3",
    title_easy_loop_mp3  : "res/sounds/blaues_titelbild_loop0,1,14.mp3",
    mostafa_out_mp3 :      "res/sounds/mostafa_geht0,1,5.mp3",
    mostafa_in_mp3 :       "res/sounds/mostafa_kommt0,1,5.mp3",
    speech_bubble_mp3 :    "res/sounds/sprechblase1,1,5.mp3",
    tutorial_again_mp3 :   "res/sounds/tutorial_nochmal1,1,4.mp3",

    // level 1
    red_noses_background_intro_mp3:             "res/sounds/levelsounds/red_noses_background_C-intro_1,3,3.mp3",
    red_noses_background_loop_C_1_mp3:           "res/sounds/levelsounds/red_noses_background_C_loop_1,4,2.mp3",
    red_noses_background_loop_C_2_mp3:           "res/sounds/levelsounds/red_noses_background_C_loop_1,4,3.mp3",
    red_noses_background_loop_F_mp3:           "res/sounds/levelsounds/red_noses_background_F_loop_1,4,2.mp3",
    red_noses_background_full_word_1_mp3:       "res/sounds/levelsounds/red_noses_background_C-F_transsition_1,3,5.mp3",
    red_noses_background_full_word_2_mp3:       "res/sounds/levelsounds/red_noses_background_F-C_transsition_1,3,6.mp3",
    red_noses_set_tile_1a_mp3:                   "res/sounds/levelsounds/red_noses_C_set_tile_a_1,1,5.mp3",
    red_noses_set_tile_1b_mp3:                   "res/sounds/levelsounds/red_noses_C_set_tile_b_1,1,5.mp3",
    red_noses_set_tile_2_mp3:                   "res/sounds/levelsounds/red_noses_F_set_tile_1,1,2.mp3",
    red_noses_rotate_1a_mp3:                    "res/sounds/levelsounds/red_noses_C_rotate_a_1,2,2.mp3",
    red_noses_rotate_1b_mp3:                    "res/sounds/levelsounds/red_noses_C_rotate_b_1,2,2.mp3",
    red_noses_rotate_1c_mp3:                    "res/sounds/levelsounds/red_noses_C_rotate_c_1,2,2.mp3",
    red_noses_rotate_1d_mp3:                    "res/sounds/levelsounds/red_noses_C_rotate_d_1,2,2.mp3",
    red_noses_rotate_1e_mp3:                    "res/sounds/levelsounds/red_noses_C_rotate_e_1,2,2.mp3",
    red_noses_rotate_1f_mp3:                    "res/sounds/levelsounds/red_noses_C_rotate_f_1,2,2.mp3",
    red_noses_rotate_1g_mp3:                    "res/sounds/levelsounds/red_noses_C_rotate_g_1,2,3.mp3",
    red_noses_rotate_1h_mp3:                    "res/sounds/levelsounds/red_noses_C_rotate_h_1,2,3.mp3",
    red_noses_fix_tile_1_mp3:                   "res/sounds/levelsounds/red_noses_C_fix_tile_1,1,4.mp3",
    red_noses_fix_tile_2_mp3:                   "res/sounds/levelsounds/red_noses_F_fix_tile_1,1,2.mp3",
    red_noses_swipe_1a_mp3:                     "res/sounds/levelsounds/red_noses_C_swipe_a_1,1,4.mp3",
    red_noses_swipe_1b_mp3:                     "res/sounds/levelsounds/red_noses_C_swipe_b_1,1,4.mp3",
    red_noses_swipe_1c_mp3:                     "res/sounds/levelsounds/red_noses_C_swipe_c_1,1,4.mp3",
    red_noses_swipe_2a_mp3:                     "res/sounds/levelsounds/red_noses_F_swipe_a_1,1,2.mp3",
    red_noses_swipe_2b_mp3:                     "res/sounds/levelsounds/red_noses_F_swipe_b_1,1,2.mp3",
    red_noses_full_word_1_mp3:                  "res/sounds/levelsounds/red_noses_C_full_word_1,1,4.mp3",
    red_noses_full_word_2_mp3:                  "res/sounds/levelsounds/red_noses_F_full_word_1,1,3.mp3",
    red_noses_selection_1_mp3:                  "res/sounds/levelsounds/red_noses_C_selection_1,1,4.mp3",
    red_noses_selection_2_mp3:                  "res/sounds/levelsounds/red_noses_F_selection_1,1,3.mp3",
    red_noses_delete_row_1_mp3:                 "res/sounds/levelsounds/red_noses_C_delete_row_1,1,4.mp3",
    red_noses_delete_row_2_mp3:                 "res/sounds/levelsounds/red_noses_F_delete_row_1,1,4.mp3",
    red_noses_delete_last_row_1_mp3:            "res/sounds/levelsounds/red_noses_C_delete_last_row_1,1,4.mp3",

    // level 2
    flames_intro_mp3:                  "res/sounds/levelsounds/flammen_hintergrund_einleitung0,1,9.mp3",
    flames_loop_mp3:                   "res/sounds/levelsounds/flammen_hintergrund_loop0,1,9.mp3",
    flames_level_words_mp3:            "res/sounds/levelsounds/flammen_drei_worte0,1,3.mp3",
    flames_level_nr_mp3:               "res/sounds/levelsounds/flammen_levelzahl0,1,7.mp3",
    flames_set_tile_mp3:               "res/sounds/levelsounds/flammen_buchstaben_neu0,1,3.mp3",
    //flames_swipe_1_mp3:                "res/sounds/none.mp3",
    //flames_swipe_2_mp3:                "res/sounds/none.mp3",
    //flames_swipe_3_mp3:                "res/sounds/none.mp3",
    flames_rotate_1_mp3:               "res/sounds/levelsounds/flammen_drehen1,1,3.mp3",
    flames_rotate_2_mp3:               "res/sounds/levelsounds/flammen_drehen2,1,3.mp3",
    flames_rotate_3_mp3:               "res/sounds/levelsounds/flammen_drehen3,1,5.mp3",
    flames_fix_tile_1_mp3:             "res/sounds/levelsounds/flammen_buchstaben_unten0,1,5.mp3",
    flames_selection_mp3:              "res/sounds/levelsounds/flammen_buchstabenkombi0,1,3.mp3",
    flames_full_word_mp3:              "res/sounds/levelsounds/flammen_wort_fertig0,1,9.mp3",
    //flames_last_word_mp3:              "res/sounds/none.mp3",
    flames_delete_row_mp3:             "res/sounds/levelsounds/flammen_reihe_kracht0,1,7.mp3",
    flames_delete_last_rows_mp3:        "res/sounds/levelsounds/flammen_reihe_kracht0,1,7.mp3",
    flames_final_mp3:                  "res/sounds/levelsounds/flammen_reihe_kracht0,1,7.mp3",

    // level 3
    test_background_loop_mp3:               "res/sounds/levelsounds/test_background1,1.mp3",
    test_background_loop1_mp3:              "res/sounds/levelsounds/test_background1,1a.mp3",
    test_set_tile_1_mp3:                    "res/sounds/levelsounds/test_trumpet_1.mp3",
    test_set_tile_2_mp3:                    "res/sounds/levelsounds/test_trumpet_2.mp3",
    test_set_tile_3_mp3:                    "res/sounds/levelsounds/test_trumpet_3.mp3",
    test_set_tile_4_mp3:                    "res/sounds/levelsounds/test_trumpet_4.mp3",
    test_rotate_1_mp3:                      "res/sounds/levelsounds/test_horns_down_1.mp3",
    test_rotate_2_mp3:                      "res/sounds/levelsounds/test_horns_down_2.mp3",
    test_rotate_3_mp3:                      "res/sounds/levelsounds/test_horns_down_3.mp3",
    test_rotate_4_mp3:                      "res/sounds/levelsounds/test_horns_down_4.mp3",
    test_fix_tile_1_mp3:                    "res/sounds/levelsounds/test_trombone_1.mp3",
    test_fix_tile_2_mp3:                    "res/sounds/levelsounds/test_trombone_2.mp3",
    test_fix_tile_3_mp3:                    "res/sounds/levelsounds/test_trombone_3.mp3",
    test_fix_tile_4_mp3:                    "res/sounds/levelsounds/test_trombone_4.mp3",

    // level 4                                               
    green_forest_intro_mp3:           "res/sounds/levelsounds/green_forest_intro_1,1,2.mp3",
    green_forest_loop_mp3:            "res/sounds/levelsounds/green_forest_loop_1,1,2.mp3",
    red_hills_level_words_mp3:        "res/sounds/levelsounds/rote_huegel_drei_worte0,1,7.mp3",
    red_hills_level_nr_mp3:           "res/sounds/levelsounds/rote_huegel_levelzahl0,1,8.mp3",
    red_hills_set_tile_mp3:           "res/sounds/levelsounds/rote_huegel_buchstaben_neu0,1,8.mp3",
    red_hills_swipe_1_mp3:            "res/sounds/levelsounds/rote_huegel_wischen_a1,1,5.mp3",
    red_hills_swipe_2_mp3:            "res/sounds/levelsounds/rote_huegel_wischen_b2,1,10.mp3",
    red_hills_swipe_3_mp3:            "res/sounds/levelsounds/rote_huegel_wischen_c3,1,5.mp3",
    red_hills_rotate_1_mp3:           "res/sounds/levelsounds/rote_huegel_drehen_a1,1,7.mp3",
    red_hills_rotate_2_mp3:           "res/sounds/levelsounds/rote_huegel_drehen_b2,1,6.mp3",
    red_hills_rotate_3_mp3:           "res/sounds/levelsounds/rote_huegel_drehen_c3,1,8.mp3",
    red_hills_fix_tile_1_mp3:         "res/sounds/levelsounds/rote_huegel_buchstaben_unten 0,1,6.mp3",
    red_hills_selection_mp3:          "res/sounds/levelsounds/rote_huegel_buchstabenkombi0,1,3.mp3",
    red_hills_full_word_mp3:          "res/sounds/levelsounds/rote_huegel_wort_fertig0,1,5.mp3",
    red_hills_last_word_mp3:          "res/sounds/levelsounds/rote_huegel_letztes_wort_fertig0,1,15.mp3",
    red_hills_delete_row_mp3:         "res/sounds/levelsounds/rote_huegel_reihe_kracht0,1,7.mp3",
    red_hills_delete_last_rows_mp3:   "res/sounds/levelsounds/rote_huegel_reihe_kracht0,1,7.mp3",
    red_hills_final_mp3:              "res/sounds/levelsounds/rote_huegel_schluss_fanfare1,1,5.mp3",

    // level 5
    //blue_quadrat_intro_mp3:                  "res/sounds/none.mp3",
    blue_quadrat_loop_mp3:                   "res/sounds/levelsounds/L5_blaues_quadrat_hintergrund_loop1,1,2.mp3",
    blue_quadrat_level_words_mp3:            "res/sounds/levelsounds/L5_blaues_quadrat_wort_fertig_b_1,1,2.mp3",
    blue_quadrat_level_nr_mp3:               "res/sounds/levelsounds/L5_blaues_quadrat_letztes_wort_1,1,2.mp3",
    blue_quadrat_set_tile_1_mp3:               "res/sounds/levelsounds/L5_blaues_quadrat_buchstaben_oben_a_1,1,2.mp3",
    blue_quadrat_set_tile_2_mp3:               "res/sounds/levelsounds/L5_blaues_quadrat_buchstaben_oben_b_1,1,2.mp3",
    blue_quadrat_set_tile_3_mp3:               "res/sounds/levelsounds/L5_blaues_quadrat_buchstaben_oben_c_1,1,2.mp3",
    //blue_quadrat_swipe_1_mp3:                "res/sounds/none.mp3",
    //blue_quadrat_swipe_2_mp3:                "res/sounds/none.mp3",
    //blue_quadrat_swipe_3_mp3:                "res/sounds/none.mp3",
    blue_quadrat_rotate_1_mp3:               "res/sounds/levelsounds/L5_blaues_quadrat_buchstaben_drehen_a_1,1,2.mp3",
    blue_quadrat_rotate_2_mp3:               "res/sounds/levelsounds/L5_blaues_quadrat_buchstaben_drehen_b_1,1,2.mp3",
    blue_quadrat_rotate_3_mp3:               "res/sounds/levelsounds/L5_blaues_quadrat_buchstaben_drehen_c_1,1,2.mp3",
    blue_quadrat_fix_tile_1_mp3:             "res/sounds/levelsounds/L5_blaues_quadrat_buchstaben_unten_a_1,1,2.mp3",
    blue_quadrat_fix_tile_2_mp3:             "res/sounds/levelsounds/L5_blaues_quadrat_buchstaben_unten_b_1,1,2.mp3",
    blue_quadrat_fix_tile_3_mp3:             "res/sounds/levelsounds/L5_blaues_quadrat_buchstaben_unten_c_1,1,2.mp3",
    blue_quadrat_selection_1_mp3:              "res/sounds/levelsounds/L5_blaues_quadrat_buchstaben_kombi_a_1,1,2.mp3",
    blue_quadrat_selection_2_mp3:              "res/sounds/levelsounds/L5_blaues_quadrat_buchstaben_kombi_b_1,1,2.mp3",
    blue_quadrat_selection_3_mp3:              "res/sounds/levelsounds/L5_blaues_quadrat_buchstaben_kombi_c_1,1,2.mp3",
    blue_quadrat_full_word_1_mp3:              "res/sounds/levelsounds/L5_blaues_quadrat_wort_fertig_a_1,1,2.mp3",
    blue_quadrat_full_word_2_mp3:              "res/sounds/levelsounds/L5_blaues_quadrat_wort_fertig_b_1,1,2.mp3",
    blue_quadrat_last_word_mp3:              "res/sounds/levelsounds/L5_blaues_quadrat_wort_fertig_a_1,1,2.mp3",
    blue_quadrat_delete_row_mp3:             "res/sounds/levelsounds/L5_blaues_quadrat_reihe_kracht_a_1,1,2.mp3",
    blue_quadrat_delete_last_rows_mp3:        "res/sounds/levelsounds/L5_blaues_quadrat_buchstaben_unten_a_1,1,2.mp3",
    blue_quadrat_final_mp3:                  "res/sounds/levelsounds/L5_blaues_quadrat_letztes_wort_1,1,2.mp3",

    // level 6
    inka_temple_intro_a_mp3:           "res/sounds/levelsounds/inka_tempel_hintergrund_a1,1,2.mp3",
    inka_temple_intro_b_mp3:           "res/sounds/levelsounds/inka_tempel_hintergrund_b1,1,2.mp3",
    inka_temple_intro_c_mp3:           "res/sounds/levelsounds/inka_tempel_hintergrund_c1,1,2.mp3",
    inka_temple_intro_d_mp3:           "res/sounds/levelsounds/inka_tempel_hintergrund_d1,1,2.mp3",
    inka_temple_intro_e_mp3:           "res/sounds/levelsounds/inka_tempel_hintergrund_e1,1,3.mp3",
    inka_temple_intro_f_mp3:           "res/sounds/levelsounds/inka_tempel_hintergrund_f1,1,2.mp3",
    inka_temple_intro_g_mp3:           "res/sounds/levelsounds/inka_tempel_hintergrund_g1,1,2.mp3",
    inka_temple_intro_h_mp3:           "res/sounds/levelsounds/inka_tempel_hintergrund_h1,1,2.mp3",
    inka_temple_level_words_mp3:       "res/sounds/levelsounds/blaue_berge_drei_worte0,1,1.mp3",
    inka_temple_level_nr_mp3:          "res/sounds/levelsounds/blaue_berge_levelzahl0,1,1.mp3",
    inka_temple_set_tile_a_mp3:        "res/sounds/levelsounds/inka_tempel_buchstaben_neu_a-c1,1,4.mp3",
    inka_temple_set_tile_b_mp3:        "res/sounds/levelsounds/inka_tempel_buchstaben_neu_d1,1,4.mp3",
    inka_temple_swipe_a_mp3:           "res/sounds/levelsounds/inka_tempel_wischen_a1,1,2.mp3",
    inka_temple_swipe_b_mp3:           "res/sounds/levelsounds/inka_tempel_wischen_b2,1,2.mp3",
    inka_temple_rotate_1_mp3:          "res/sounds/levelsounds/inka_tempel_drehen_a1,1,4.mp3",
    inka_temple_rotate_2_mp3:          "res/sounds/levelsounds/inka_tempel_drehen_b2,1,4.mp3",
    inka_temple_rotate_3_mp3:          "res/sounds/levelsounds/inka_tempel_drehen_c3,1,4.mp3",
    inka_temple_fix_tile_a_mp3:        "res/sounds/levelsounds/inka_tempel_buchstaben_unten_a+d1,1,2.mp3",
    inka_temple_fix_tile_b_mp3:        "res/sounds/levelsounds/inka_tempel_buchstaben_unten_b2,1,2.mp3",
    inka_temple_fix_tile_c_mp3:        "res/sounds/levelsounds/inka_tempel_buchstaben_unten_c3,1,2.mp3",
    inka_temple_selection_mp3:         "res/sounds/levelsounds/inka_tempel_buchstabenkombi_0,1,3.mp3",
    inka_temple_full_word_mp3:         "res/sounds/levelsounds/inka_tempel_wort_fertig_a1,1,2.mp3",
    inka_temple_last_word_mp3:         "res/sounds/levelsounds/inka_tempel_wort_fertig_a1,1,2.mp3",
    //inka_temple_delete_row_mp3:        "",
    //inka_temple_delete_last_rows_mp3:        "",
    inka_temple_present_word_mp3:      "res/sounds/levelsounds/inka_tempel_wort_waehlen_warten0,1,3.mp3",
    inka_temple_next_word_mp3:         "res/sounds/levelsounds/inka_tempel_wort_gewaehlt_a+b1,1,2.mp3",  
    inka_temple_final_mp3:      	   "res/sounds/levelsounds/inka_tempel_abschluss0,1,16.mp3",
        
    // level 7
    blue_mountains_intro_mp3:           "res/sounds/levelsounds/blau_berge_einleitung1,1,9.mp3",
    blue_mountains_loop_a_mp3:          "res/sounds/levelsounds/blau_berge_loop_a_2,2,1.mp3",
    blue_mountains_loop_b_mp3:          "res/sounds/levelsounds/blau_berge_loop_b_2,2,1.mp3",
    blue_mountains_level_words_mp3:     "res/sounds/levelsounds/blaue_berge_drei_worte0,1,1.mp3",
    blue_mountains_level_nr_mp3:        "res/sounds/levelsounds/blaue_berge_levelzahl0,1,1.mp3",
    blue_mountains_set_tile_mp3:        "res/sounds/levelsounds/blaue_berge_buchstaben_neu0,1,5.mp3",
    blue_mountains_swipe_mp3:           "res/sounds/levelsounds/blaue_berge_wischen0,1,17.mp3",
    blue_mountains_rotate_1_mp3:        "res/sounds/levelsounds/blaue_berge_drehen1,1,9.mp3",
    blue_mountains_rotate_2_mp3:        "res/sounds/levelsounds/blaue_berge_drehen2,1,9.mp3",
    blue_mountains_rotate_3_mp3:        "res/sounds/levelsounds/blaue_berge_drehen3,1,9.mp3",
    blue_mountains_fix_tile_1_mp3:      "res/sounds/levelsounds/blaue_berge_buchstaben_unten1,1,4.mp3",  
    blue_mountains_fix_tile_2_mp3:      "res/sounds/levelsounds/blaue_berge_buchstaben_unten3,1,4.mp3",
    blue_mountains_selection_mp3:       "res/sounds/levelsounds/blaue_berge_buchstabenkombi0,1,5.mp3",
    blue_mountains_full_word_mp3:       "res/sounds/levelsounds/blaue_berge_wort_fertig0,1,9.mp3",
    blue_mountains_last_word_mp3:       "res/sounds/levelsounds/blaue_berge_letztes_wort_fertig0,1,7.mp3",
    blue_mountains_delete_row_mp3:      "res/sounds/levelsounds/blaue_berge_reihe_kracht0,1,4.mp3",
    blue_mountains_delete_last_rows_mp3:      "res/sounds/levelsounds/blaue_berge_reihe_kracht0,1,4.mp3",
    blue_mountains_present_word_mp3:    "res/sounds/levelsounds/blaue_berge_wort_praesentieren0,1,17.mp3",
    blue_mountains_final_mp3:      	    "res/sounds/levelsounds/blaue_berge_schlussfanfare0,1,9.mp3",

    // fonts
	amtype24_fnt : "res/fonts/amtype24.fnt",
	amtype72_fnt : "res/fonts/amtype72.fnt",
	american_typewriter_ttf: "res/fonts/American Typewriter.ttf",
	//exo_bold_ttf: {type:"font", name:"Exo", srcs:["res/fonts/Exo-Bold.ttf"]},
	exo_regular_ttf:        {type:"font", name:"Exo", srcs:["res/fonts/Exo-Regular.ttf"]},
    shadows_into_light_ttf: {type:"font", name:"Shadows Into Light", srcs:["res/fonts/ShadowsIntoLight.ttf"]},
	
	// murbiks / tutorial
    murbiks_single_png : "res/images/murbiks/mostafa_fly01.png",
    murbiks_png : "res/images/murbiks/murbiks.png",
    murbiks_plist : "res/images/murbiks/murbiks.plist",
    
    // particles
    particle_flowers: "res/particles/Flower.plist",

    // language resources
    language_pack:      "res/i18n/language-pack-de_DE.json",
    language_words:     "res/words/derewo57000.txt.words.json",
    language_letters:   "res/words/derewo57000.txt.letters.json",
    language_prefixes:  "res/words/derewo57000.txt.prefixes.json",
    language_shorties:  "res/words/derewo57000.txt.shorties.json",

    //language_pack: "language-pack-en_US.json",
    //language_pack: "language-pack-ee_EE.json",
    //language_pack: "language-pack-se_SE.json"
};

var g_resources = [];
for (var r in res) {
    g_resources.push(res[r]);
}

